### ISSUE TITLE
loading error on startup

### ISSUE THREAD

**Issue by antoniusz** [anitagraser/qgis-processing-trajectory#6]
Hi,

I've got this error on startup:

ModuleNotFoundError: No module named 'processing_trajectory' 
Traceback (most recent call last):
  File "/home/toni/FLOSS/qgis/apps_r34/share/qgis/python/qgis/utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "/home/toni/FLOSS/qgis/apps_r34/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-processing-trajectory/__init__.py", line 28, in 
    from .qgis_processing.trajectoryProviderPlugin import TrajectoryProviderPlugin
  File "/home/toni/FLOSS/qgis/apps_r34/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-processing-trajectory/qgis_processing/trajectoryProviderPlugin.py", line 26, in 
    from .trajectoryProvider import TrajectoryProvider
  File "/home/toni/FLOSS/qgis/apps_r34/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-processing-trajectory/qgis_processing/trajectoryProvider.py", line 30, in 
    from .trajectoriesFromPointLayerAlgorithm import TrajectoriesFromPointLayerAlgorithm
  File "/home/toni/FLOSS/qgis/apps_r34/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-processing-trajectory/qgis_processing/trajectoriesFromPointLayerAlgorithm.py", line 52, in 
    from processing_trajectory.trajectory import Trajectory
  File "/home/toni/FLOSS/qgis/apps_r34/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'processing_trajectory'

Python verzió: 3.7.2 (default, Jan  3 2019, 02:55:40) [GCC 8.2.0] 
QGIS verzió 3.4.4-Madeira Madeira, 20cd215435

**Comment by anitagraser** [comment]
Renaming the folder `python/plugins/qgis-processing-trajectory` to `python/plugins/processing_trajectory` should fix this

**Comment by antoniusz** [comment]
Thanks!
